# -*- coding: utf-8 -*-
"""ImageCraftAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hAaM5Onsv5FJy7O3CdrVPP3sSNzSX8Q1
"""

!pip install transformers diffusers torch pillow gradio

from diffusers import StableDiffusionPipeline
import torch
import gradio as gr
from PIL import Image

# Load the model
model_id = "runwayml/stable-diffusion-v1-5"
token = "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"
pipe = StableDiffusionPipeline.from_pretrained(model_id, use_auth_token=token, torch_dtype=torch.float16)
pipe.to("cuda")  # Move model to GPU

def generate_image(prompt):
    image = pipe(prompt).images[0]  # Generate image
    return image  # Return generated image

interface = gr.Interface(
    fn=generate_image,
    inputs=gr.Textbox(label="Enter Image Description"),
    outputs=gr.Image(label="Generated Image"),
    title="Image Craft AI",
    description="Enter a descriptive text to generate an image."
)

interface.launch(share = True, debug=True)